PARENT: "tum.yml"
META:
    OUTPUT_DIR: "data"
    NAME_EXPERIMENT: "TUM_xyz"
    RUN_ID: 0
DATASET:
    NAME: "TUMDatasetInstantNGP"
    INPUT_FOLDER: "Datasets/TUM_RGBD/rgbd_dataset_freiburg2_xyz"
    CROP_SIZE:
        ENABLED: True
        VALUE: [384,512]
    CROP_EDGE:
        ENABLED: True
        VALUE: 8
    PNG_DEPTH_SCALE: 5000.0
    POSES_FILENAME: "data/TUM_xyz/0/poses_processed_NGP.json"
    SHARPNESS_FILENAME: "data/TUM_xyz/0/preprocess_sharpness.json"
    NGP_PREPROCESSED_DATA_FILENAME: "data/TUM_xyz/0/preprocessed_dataset/transforms_with_poses.json"
    POSES_SCALE: 9.077644078501473
    POSES_CENTER_POINT: [-0.22524409, -0.08434618, 0.06836408]
    POSES_UP_VECTOR: [-0.99337919, -0.11426673, -0.01187021]
    DESIRED_RESOLUTION: 528 #(1.97cm rez)
    FRAME_SAMPLING_RATE: 1
    KEEP_DATA_ON_CPU: False
RENDERER: #here for the hyper-params
    NAME: "RendererInstantNGP" # implemented in NGP
    IMAGE_H: 480
    IMAGE_W: 640
    FX: 520.9
    FY: 521.0
    CX: 325.1
    CY: 249.7
    SCALE: 0.010561658888026002
    OFFSET: [0.89901611, 0.65546238, 0.13469382]
    AABB_SCALE: 1
    DISTORTION:
        ENABLED: True
        PARAMS: [0.2312, -0.7849, -0.0033, -0.0001, 0.9172]
VERSION: 2
