# Copyright (c) Facebook, Inc. and its affiliates.
from .config import CfgNode as CN

# -----------------------------------------------------------------------------
# Config definition
# -----------------------------------------------------------------------------

_C = CN()

# The version number, to upgrade from old configs to new ones if any
# changes happen. It's recommended to keep a VERSION in your config file.
_C.VERSION = 2

_C.PARENT = ""

_C.META = CN()
_C.META.OUTPUT_DIR = ""
_C.META.NAME_EXPERIMENT= ""
_C.META.RUN_ID= 0

_C.MODEL = CN()
_C.MODEL.NERF_ARCHITECTURE = "Nerf"
_C.MODEL.DEVICE = "cuda"
_C.MODEL.HIDDEN_SIZE = 256
_C.MODEL.N_BLOCKS = 8
_C.MODEL.SKIPS = [4]
_C.MODEL.USE_VIEW_DIRS = False
_C.MODEL.CAMERA_EMBEDDING_DIM = -1
_C.MODEL.POSE_EMBEDDING = CN()
_C.MODEL.POSE_EMBEDDING.NAME = "FourierEmbedder"
_C.MODEL.POSE_EMBEDDING.MULTIRES = 9
_C.MODEL.POSE_EMBEDDING.LOG_SAMPLING = False
_C.MODEL.POSE_EMBEDDING.MAX_DEG = 16
_C.MODEL.POSE_EMBEDDING.MIN_DEG = 0

_C.MODEL.POSE_EMBEDDING.SIZE = 93
_C.MODEL.POSE_EMBEDDING.STD = 25.0
_C.MODEL.POSE_EMBEDDING.LEARNABLE = False
_C.MODEL.MESH_RESOLUTION = 256
_C.MODEL.MESH_THRESH = 2.5
_C.MODEL.MESH_RESOLUTION_METERS = -1.0
_C.MODEL.USE_MCB_IN_MESHING = False
_C.MODEL.USE_CONVEX_HULL_FILTER_IN_MARCHING_CUBES = False

# Path (a file path, or URL like detectron2://.., https://..) to a checkpoint file
# to be loaded to the model. You can find available models in the model zoo.
_C.MODEL.WEIGHTS = ""

#NICE_SLAM configs
_C.MODEL.USE_COARSE = False
_C.MODEL.GRID_FEATURE_DIM = 32
_C.MODEL.GRID_RESOLUTION_COARSE = 2.0
_C.MODEL.GRID_RESOLUTION_MIDDLE = 0.16
_C.MODEL.GRID_RESOLUTION_FINE = 0.16
_C.MODEL.GRID_RESOLUTION_COLOR = 0.16
_C.MODEL.PRETRAIN_DECODER_WEIGHTS_COARSE = ""
_C.MODEL.PRETRAIN_DECODER_WEIGHTS_MIDDLE_FINE = ""

# INSTANT_NGP configs
_C.MODEL.INSTANT_NGP_CONFIG_FILE = ""
_C.MODEL.DEPTH_SUPERVISION_LAMBDA = 0.
_C.MODEL.DEPTH_SUPERVISION_LAMBDA_TRACKING = 0.
_C.MODEL.RGB_SUPERVISION_LAMBDA = 1.
_C.MODEL.RGB_SUPERVISION_LAMBDA_TRACKING = 1.
_C.MODEL.USE_FREE_SPACE_LOSS = False
_C.MODEL.USE_FREE_SPACE_LOSS_TRACKING = False
_C.MODEL.FREE_SPACE_SUPERVISION_LAMBDA = 0.
_C.MODEL.FREE_SPACE_SUPERVISION_LAMBDA_TRACKING = 0.
_C.MODEL.FREE_SPACE_SUPERVISION_DISTANCE = 0.05

#SDF stuff
_C.MODEL.USE_SDF = False
_C.MODEL.USE_VOL_SDF = False
_C.MODEL.USE_STYLE_SDF = False
_C.MODEL.USE_COSLAM_SDF = False
_C.MODEL.SDF_TRUNCATION_DISTANCE = 0.1
_C.MODEL.SDF_BETA = 0.1
_C.MODEL.USE_SDF_LOSS = False
_C.MODEL.USE_SDF_LOSS_TRACKING = False
_C.MODEL.SDF_SUPERVISION_LAMBDA = 0.0
_C.MODEL.SDF_SUPERVISION_LAMBDA_TRACKING = 0.0
_C.MODEL.USE_SDF_FREE_SPACE_LOSS = False
_C.MODEL.USE_SDF_FREE_SPACE_LOSS_TRACKING = False
_C.MODEL.SDF_FREE_SPACE_SUPERVISION_LAMBDA = 0.0
_C.MODEL.SDF_FREE_SPACE_SUPERVISION_LAMBDA_TRACKING = 0.0


_C.MODEL.USE_DEPTH_GUIDED_SAMPLING = False
_C.MODEL.TRUNCATION_DISTANCE_FOR_DEPTH_GUIDED_SAMPLING = 0.05
_C.MODEL.NUM_SAMPLES_FOR_DEPTH_GUIDED_SAMPLING = 16

_C.MODEL.USE_CUSTOM_RAY_MARCHING = False
_C.MODEL.N_SAMPLES_FOR_REGULAR_POINT_SAMPLING = 128

_C.MODEL.USE_POSE_SCHEDULER_IN_MAPPING = False
_C.MODEL.POSE_SCHEDULER_COEF = 0.33
_C.MODEL.POSE_SCHEDULER_NORM = 128

_C.MODEL.CONE_ANGLE_CONSTANT = 0.

_C.MODEL.USE_GRADIENT_CLIPPING_EXTRINSICS = False
_C.MODEL.DENSITY_GRID_DECAY = 0.95
_C.MODEL.USE_DENSITY_IN_POINT_SAMPLING = True

_C.MODEL.USE_DS_NERF_LOSS = False
_C.MODEL.USE_DS_NERF_LOSS_TRACKING = False
_C.MODEL.DS_NERF_LOSS_LAMBDA = 0.
_C.MODEL.DS_NERF_LOSS_LAMBDA_TRACKING = 0.
_C.MODEL.DS_NERF_LOSS_DEPTH_SIGMA = 0.
_C.MODEL.DS_NERF_USE_SECH2_DIST = False
_C.MODEL.DS_NERF_SECH2_SCALE = 1.0
_C.MODEL.DS_NERF_SECH2_NORM = 1.0
_C.MODEL.DS_NERF_SECH2_INT_A = 1.0
_C.MODEL.DS_NERF_SECH2_INT_B = 1.0

_C.MODEL.DENSITY_ACTIVATION = "Exponential"

_C.MODEL.USE_MEDIAN_DEPTH = False

_C.MODEL.DO_MULTI_POS_ENCODING = False

_C.MODEL.MAX_NUM_STEPS_PER_RAY = 1024
_C.MODEL.NUM_STEPS_RESOLUTION_METERS = 0.0

_C.MAPPER = CN()
_C.MAPPER.NAME = "MapperDefault"
_C.MAPPER.NUM_PIXELS_PER_ITER = 10
_C.MAPPER.LR = 0.0002
_C.MAPPER.MAPPING_ITERATIONS = 2000
_C.MAPPER.GET_SAMPLES_USING_DEPTH = False
_C.MAPPER.KEYFRAME_SELECTION_METHOD = "global"
_C.MAPPER.MARGIN_SAMPLE_WIDTH = 0
_C.MAPPER.MARGIN_SAMPLE_HEIGHT= 0
_C.MAPPER.DO_BA_WHILE_MAPPING= False
_C.MAPPER.DO_BA_WHILE_LOCAL_MAPPING= False
_C.MAPPER.EXTRINSIC_LEARNING_RATE = 1e-3
_C.MAPPER.EXTRINSIC_LEARNING_RATE_POS = 1e-3
_C.MAPPER.EXTRINSIC_LEARNING_RATE_ROT = 1e-3
_C.MAPPER.MAX_GRID_LEVEL_RAND_TRAINING= False
_C.MAPPER.MAX_GRID_LEVEL_FACTOR = 2.0
_C.MAPPER.NUM_RAYS_TO_SAMPLE= 4096
_C.MAPPER.NO_NUM_RAYS_IMPOSED_ON_FIRST_FRAME = False
_C.MAPPER.SAMPLE_IMAGE_PROPORTIONAL_TO_ERROR = False
_C.MAPPER.NUM_STEPS_BETWEEN_ERROR_MAP_UPDATE = 128
_C.MAPPER.LOSS = CN()
_C.MAPPER.LOSS.NAME = "MappingLossColorDepth"
_C.MAPPER.LOSS.COLOR_WEIGHT = 0.2
_C.MAPPER.LOSS.DEPTH_WEIGHT = 1.0
_C.MAPPER.LOSS.DENSITIES_WEIGHT = 1000000000.0
_C.MAPPER.LOSS.SCALE = 100.0 # to make it mm in loss

_C.MAPPER.LOSS.IMAP_WINDOW_WIDTH = 80
_C.MAPPER.LOSS.IMAP_WINDOW_HEIGHT = 60

_C.MAPPER.TRACKING_HYPERPARAMETERS_FILE = ""
# -- some iNGP settings
_C.MAPPER.TARGET_BATCH_SIZE = 256000
_C.MAPPER.N_STEPS_BETWEEN_CAM_UPDATES = 8
_C.MAPPER.BA_MODE = 1

_C.MAPPER.MAX_FRAMES_PER_ITER = 5
# MAPPING EARLY STOP
_C.MAPPER.EARLY_STOP = CN()
_C.MAPPER.EARLY_STOP.MV_AVG_K = 30
_C.MAPPER.EARLY_STOP.MIN_MAPPING_ITER = 500
_C.MAPPER.EARLY_STOP.GRAD_WINDOW_K = 30
_C.MAPPER.EARLY_STOP.THRESH = 3.0

_C.MAPPER.DO_LOCAL_MAPPING = False
_C.MAPPER.LOCAL_MAPPING_ITERATIONS = 32

_C.MAPPER.DEBUG = False


_C.TRACKER = CN()
_C.TRACKER.NAME = "TrackerDefault"
_C.TRACKER.SEPARATE_POS_AND_ROT_LR = False
_C.TRACKER.POS_LR = 0.01
_C.TRACKER.ROT_LR = 0.002
_C.TRACKER.LR = 0.001
_C.TRACKER.TRACKING_ITERATIONS= 2000
_C.TRACKER.MARGIN_SAMPLE_WIDTH = 20
_C.TRACKER.MARGIN_SAMPLE_HEIGHT = 20
_C.TRACKER.NUM_PIXELS_PER_ITER = 10
_C.TRACKER.TRACKING_RESOLUTION_H = 240
_C.TRACKER.TRACKING_RESOLUTION_W = 320
_C.TRACKER.GET_SAMPLES_USING_DEPTH = False
_C.TRACKER.NUM_RAYS_TO_SAMPLE= 4096
_C.TRACKER.INSTANT_NGP_TRACKING_MODE= 0 # 0 regular, 1- Gaussian Pyramid, 2-Max-grid-levelI
_C.TRACKER.LOSS = CN()
_C.TRACKER.LOSS.NAME = "TrackingLossColorDepth"
_C.TRACKER.LOSS.COLOR_WEIGHT = 0.2
_C.TRACKER.LOSS.DEPTH_WEIGHT = 1.0
_C.TRACKER.LOSS.LK_WEIGHT = 1.0
# -- used for HLK-OF loss
_C.TRACKER.LOSS.LK_WINDOW_SIZE = 5
_C.TRACKER.LOSS.LEVELS = 5
# TACKING EARLY STOP
_C.TRACKER.EARLY_STOP = CN()
_C.TRACKER.EARLY_STOP.MV_AVG_K = 5
_C.TRACKER.EARLY_STOP.MIN_TRACKING_ITER = 30
_C.TRACKER.EARLY_STOP.GRAD_WINDOW_K = 10
_C.TRACKER.EARLY_STOP.THRESH = 0.1
_C.TRACKER.TRACKING_HYPERPARAMETERS_FILE = ""
_C.TRACKER.USE_DEPTH_VAR_IN_DEPTH_LOSS = False
_C.TRACKER.USE_IF_LOSS = False
_C.TRACKER.TARGET_BATCH_SIZE = 256000
_C.TRACKER.DEBUG = False

_C.RENDERER = CN()
_C.RENDERER.NAME = "RendererDefault"

#Orginal image resolution and intrinsics. Will
# change if image is preprocessed - see
# DATASET.CROP_SIZE and DATASET.CROP_EDGE
_C.RENDERER.IMAGE_H = 480
_C.RENDERER.IMAGE_W = 640
_C.RENDERER.FX = 1.0
_C.RENDERER.FY = 1.0
_C.RENDERER.CX = 1.0
_C.RENDERER.CY = 1.0
_C.RENDERER.NEAR = 0.0
_C.RENDERER.FAR = 10.0
_C.RENDERER.NUM_SAMPLES_ALONG_RAY = 32
_C.RENDERER.NUM_SAMPLES_ALONG_RAY_FINE = 12
_C.RENDERER.SCALE = 1.0 # things are in meters in general. Can use this param to convert to mm
_C.RENDERER.MAPPING_BOUND = [[-4.6,2.6],[-3.3,3.2],[-2.0,4.9]]
_C.RENDERER.PERTURB = True
_C.RENDERER.USE_DISPARITY = False
_C.RENDERER.RAY_SHAPE = "cone"
_C.RENDERER.NUM_POINTS_PER_BATCH=256
_C.RENDERER.DISTORTION = CN({"ENABLED":False})
_C.RENDERER.DISTORTION.PARAMS = []

# Instant NGP configs
_C.RENDERER.OFFSET = [0.0,0.0,0.0]
_C.RENDERER.AABB_SCALE = 16

_C.DATASET = CN()
_C.DATASET.NAME = "TUMDataset"
_C.DATASET.INPUT_FOLDER = "Datasets/TUM_RGBD/rgbd_dataset_freiburg1_desk"
_C.DATASET.CROP_SIZE = CN({"ENABLED":False})
_C.DATASET.CROP_SIZE.VALUE = []
_C.DATASET.CROP_EDGE = CN({"ENABLED":False})
_C.DATASET.CROP_EDGE.VALUE = 0
_C.DATASET.PNG_DEPTH_SCALE = 1.0
_C.DATASET.PNG_ENCODING_DEPTH_SCALE = 1.0
_C.DATASET.FRAME_RATE = 32

# Instant NGP configs
_C.DATASET.POSES_UP_VECTOR = []
_C.DATASET.POSES_CENTER_POINT = []
_C.DATASET.POSES_AVGLEN = 0.0
_C.DATASET.POSES_SCALE = 0.0
_C.DATASET.POSES_FILENAME = ""
_C.DATASET.NGP_PREPROCESSED_DATA_FILENAME = ""
_C.DATASET.DESIRED_RESOLUTION = 2048
_C.DATASET.MARCHING_CUBES_BOUND = [[-100,100],[-100,100],[-100,100]]
_C.DATASET.FRAME_SAMPLING_RATE = 1
_C.DATASET.FRAME_SAMPLING_OFFSET = 0
_C.DATASET.KEEP_DATA_ON_CPU = False
_C.DATASET.SHARPNESS_FILENAME = ""

_C.RUNNER = CN()
_C.RUNNER.NAME = "RunnerDefault"
_C.RUNNER.SKIP_MAPPING_FIRST_IMAGE = False
_C.RUNNER.NUM_MAPPING_ITERATIONS_FIRST_IMAGE = 4000
_C.RUNNER.TARGET_BATCH_SIZE_FIRST_IMAGE = 1024000
_C.RUNNER.TRACKING_VISUALS_DIRNAME = 'tracking_viz'
_C.RUNNER.MAPPING_VISUALS_DIRNAME = 'mapping_viz'
_C.RUNNER.MODEL_CHECKPOINT_DIRNAME = 'models'
_C.RUNNER.LOGS_DIRNAME = 'logs'
_C.RUNNER.POSES_DIRNAME = 'poses'
_C.RUNNER.MESHES_DIRNAME = 'meshes'
_C.RUNNER.DEVICE_MAPPING = 'cuda:0'
_C.RUNNER.DEVICE_TRACKING = 'cuda:0'
_C.RUNNER.VIZ = False
_C.RUNNER.SAVE_VIZ_EVERY = 10
_C.RUNNER.KEYFRAME_RATE = 1
_C.RUNNER.KEYFRAME_MOTION_FILTER_THRESH = 1.5
_C.RUNNER.CONSTANT_SPEED_ASSUMPTION = False
_C.RUNNER.VERBOSE = False
_C.RUNNER.DO_ADDITIONAL_LOCAL_BA = False
_C.RUNNER.SAVE_TB_LOGS = False
_C.RUNNER.ADD_FINAL_GIANT_BA = False
_C.RUNNER.ADD_FINAL_GIANT_BA = False
_C.RUNNER.DO_ADDITIONAL_LOCAL_FINETUNING = False
_C.RUNNER.LOCAL_FINETUNING_RATE = 10
_C.RUNNER.DO_DECODER_ONLY_PRETRAINING = False
_C.RUNNER.MAPPING_RATE = 1
_C.RUNNER.USE_INITIALIZATION = False
_C.RUNNER.INITIALIZATION_ITERATIONS = 25
_C.RUNNER.SAVE_MODELS = True
_C.RUNNER.SAVE_MODELS_RATE = 1
_C.RUNNER.USE_GT_CAMERA_POSES_FOR_MAPPING = False
_C.RUNNER.KF_MOTION_BASED_SELECTION = False
_C.RUNNER.KF_SELECTION_RATE = 5
_C.RUNNER.KF_SELECTION_RATE_MAX = 100
_C.RUNNER.DO_TRACKING = True
_C.RUNNER.SAVE_MESHES = True
_C.RUNNER.SAVE_MESHES_RATE = 1
_C.RUNNER.USE_SHARPNESS_IN_KF_SELECTION = False
_C.RUNNER.SHARPNESS_THRESH = 100.
_C.RUNNER.ADD_MOTION_ONLY_BA_TRAJECTORY_FILLER = False
_C.RUNNER.MOTION_ONLY_BA_ITERATIONS = 32


_C.BUNDLE_ADJUSTMENTS = CN()

_C.BUNDLE_ADJUSTMENTS.MOTION_BA = CN()
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.NAME = "MotionBA"
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.LR = 0.01
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.SEPARATE_POS_AND_ROT_LR = False
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.POS_LR = 0.01
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.ROT_LR = 0.002
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.NUM_ITERATIONS = 500
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.NUM_PIXELS_PER_ITER = 5000
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.MARGIN_SAMPLE_WIDTH = 30
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.MARGIN_SAMPLE_HEIGHT = 30
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.DEPTH_VAR_THRESH = 0.0025 #m2
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.DEPTH_OCCLUSION_MARGIN = 0.01 #m
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.GET_SAMPLES_USING_DEPTH = False
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.MIN_NUM_POINTS_FOR_OPTIMIZATION = 10
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.EARLY_STOP = CN()
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.EARLY_STOP.MV_AVG_K = 5
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.EARLY_STOP.MIN_TRACKING_ITER = 300
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.EARLY_STOP.GRAD_WINDOW_K = 5
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.EARLY_STOP.THRESH = 1.0
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.LOSS = CN()
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.LOSS.NAME = "BALossDepth"
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.LOSS.DEPTH_VAR_THRESH = 0.0025 #m2
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.LOSS.MIN_NUM_POINTS_FOR_OPTIMIZATION = 10
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.LOSS.DEPTH_WEIGHT = 1.0
_C.BUNDLE_ADJUSTMENTS.MOTION_BA.LOSS.COLOR_WEIGHT = 1.0

_C.BUNDLE_ADJUSTMENTS.LOCAL_BA = CN()
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.NAME = "LocalBA"
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.LR = 0.01
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.MAPPING_LR = 0.01
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.SEPARATE_POS_AND_ROT_LR = False
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.POS_LR = 0.01
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.ROT_LR = 0.002
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.NUM_ITERATIONS = 500
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.NUM_PIXELS_PER_ITER = 5000
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.MARGIN_SAMPLE_WIDTH = 30
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.MARGIN_SAMPLE_HEIGHT = 30
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.MAX_FRAMES_PER_ITER = 5
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.EARLY_STOP = CN()
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.EARLY_STOP.MV_AVG_K = 5
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.EARLY_STOP.MIN_TRACKING_ITER = 300
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.EARLY_STOP.GRAD_WINDOW_K = 5
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.EARLY_STOP.THRESH = 1.0
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.LOSS = CN()
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.LOSS.NAME = "BALossColorDepth"
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.LOSS.COLOR_WEIGHT = 1.0
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.LOSS.DEPTH_WEIGHT = 1.0
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.LOSS.IMAP_WINDOW_HEIGHT = 60
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.LOSS.IMAP_WINDOW_WIDTH = 80
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.HYPERPARAMETERS_FILE = ""

# some iNGP params
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.MAX_GRID_LEVEL_RAND_TRAINING = False
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.EXTRINSIC_LEARNING_RATE = 0.001
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.SAMPLE_IMAGE_PROPORTIONAL_TO_ERROR = False
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.NUM_RAYS_TO_SAMPLE = 4096
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.TARGET_BATCH_SIZE = 256000
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.N_STEPS_BETWEEN_CAM_UPDATES = 8
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.BA_MODE = 1
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.MIN_RAYS_PER_IMAGE = 64
_C.BUNDLE_ADJUSTMENTS.LOCAL_BA.USE_RAY_COUNTERS_PER_IMAGE = False






_C.EVALUATOR = CN()
_C.EVALUATOR.NAME = "EvaluatorATE"
_C.EVALUATOR.USE_VIRT_CAMS = False

_C.VISUALIZER = CN()
_C.VISUALIZER.NAME = "VisualizerDefault"
_C.VISUALIZER.DEVICE = "cuda"
_C.VISUALIZER.MESHER = CN()
_C.VISUALIZER.MESHER.RESOLUTION = 256
_C.VISUALIZER.MESHER.MARCHING_CUBES_BOUND = [[-2.6,1.1],[-1.5,1.5],[-0.6,2.4]]
_C.VISUALIZER.MESHER.MARCHING_CUBES_LEVEL = -1.0
_C.VISUALIZER.MESHER.NUM_POINTS_PER_BATCH=500000
_C.VISUALIZER.MESHER.CLEAN_MESH=False
_C.VISUALIZER.MESHER.CLEAN_MESH_SCALE=1.0
_C.VISUALIZER.MESHER.WITH_RGB=True
_C.VISUALIZER.MESHER.USE_CONVEX_HULL=False
_C.VISUALIZER.MESHER.USE_MESH_CULLING=False
_C.VISUALIZER.MESHER.USE_CONNECTED_COMPONENTS=False
