PARENT: "scannet.yml"
META:
    OUTPUT_DIR: "data"
    NAME_EXPERIMENT: "ScanNet_scene0169"
    RUN_ID: 0
DATASET:
    NAME: "ScannetDatasetInstantNGP"
    INPUT_FOLDER: "Datasets/scannet/scans/scene0169_00"
    CROP_SIZE:
        ENABLED: False
    CROP_EDGE:
        ENABLED: True
        VALUE: 10
    PNG_DEPTH_SCALE: 1000.
    POSES_FILENAME: "data/ScanNet_scene0169/0/poses_processed_NGP.json"
    SHARPNESS_FILENAME: "data/ScanNet_scene0169/0/preprocess_sharpness.json"
    NGP_PREPROCESSED_DATA_FILENAME: "data/ScanNet_scene0169/0/preprocessed_dataset/transforms_with_poses.json"
    POSES_SCALE: 1.8086129897801357 
    POSES_CENTER_POINT: [2.39751465, 6.19371234, 0.96967279]
    POSES_UP_VECTOR: [-0.01898268, 0.01105977, -0.99975864]
    DESIRED_RESOLUTION: 304 #(4.06cm rez)
    MARCHING_CUBES_BOUND:  [[0.5,9.1],[-0.3,7.8],[-0.3,2.7]]
    FRAME_SAMPLING_RATE: 1
    KEEP_DATA_ON_CPU: False
RENDERER: #here for the hyper-params
    NAME: "RendererInstantNGP" # implemented in NGP
    IMAGE_H: 480
    IMAGE_W: 640
    FX: 577.590698
    FY: 578.729797
    CX: 318.905426
    CY: 242.683609
    SCALE: 0.04476780987933594
    OFFSET: [0.5164001, 0.28676061, 0.26078925] 
    AABB_SCALE: 1
    DISTORTION:
        ENABLED: False
    NEAR: 0.0
    FAR: 8.0
VERSION: 2
