PARENT: "scannet.yml"
META:
    OUTPUT_DIR: "data"
    NAME_EXPERIMENT: "ScanNet_scene0207"
    RUN_ID: 0
DATASET:
    NAME: "ScannetDatasetInstantNGP"
    INPUT_FOLDER: "Datasets/scannet/scans/scene0207_00"
    CROP_SIZE:
        ENABLED: False
    CROP_EDGE:
        ENABLED: True
        VALUE: 10
    PNG_DEPTH_SCALE: 1000.
    POSES_FILENAME: "data/ScanNet_scene0207/0/poses_processed_NGP.json"
    SHARPNESS_FILENAME: "data/ScanNet_scene0207/0/preprocess_sharpness.json"
    NGP_PREPROCESSED_DATA_FILENAME: "data/ScanNet_scene0207/0/preprocessed_dataset/transforms_with_poses.json"
    POSES_SCALE: 3.555331558876587
    POSES_CENTER_POINT: [5.99821449, 2.39624164, 1.21616276]
    POSES_UP_VECTOR: [ 0.06361893, -0.07182363, -0.99538636]
    DESIRED_RESOLUTION: 432 #(3.98cm rez)
    MARCHING_CUBES_BOUND: [[1.0,9.3],[-0.3,7.3],[-0.4,3.1]]
    FRAME_SAMPLING_RATE: 1
    KEEP_DATA_ON_CPU: False
RENDERER: #here for the hyper-params
    NAME: "RendererInstantNGP" # implemented in NGP
    IMAGE_H: 480
    IMAGE_W: 640
    FX: 577.590698
    FY: 578.729797
    CX: 318.905426
    CY: 242.683609
    SCALE:  0.016348686055024746
    OFFSET: [0.42997748, 0.27041729, 0.26335248] 
    AABB_SCALE: 1
    DISTORTION:
        ENABLED: False
    NEAR: 0.0
    FAR: 8.0
VERSION: 2
