PARENT: "scannet.yml"
META:
    OUTPUT_DIR: "data"
    NAME_EXPERIMENT: "ScanNet_scene0000"
    RUN_ID: 0
DATASET:
    NAME: "ScannetDatasetInstantNGP"
    INPUT_FOLDER: "Datasets/scannet/scans/scene0000_00"
    CROP_SIZE:
        ENABLED: False
    CROP_EDGE:
        ENABLED: True
        VALUE: 10
    PNG_DEPTH_SCALE: 1000.
    POSES_FILENAME: "data/ScanNet_scene0000/0/poses_processed_NGP.json"
    SHARPNESS_FILENAME: "data/ScanNet_scene0000/0/preprocess_sharpness.json"
    NGP_PREPROCESSED_DATA_FILENAME: "data/ScanNet_scene0000/0/preprocessed_dataset/transforms_with_poses.json"
    POSES_SCALE: 2.2690085423310395
    POSES_CENTER_POINT: [2.39298678, 5.55124637, 1.04430687]
    POSES_UP_VECTOR: [-0.0722404,  0.05161488, -0.99605082]
    DESIRED_RESOLUTION: 384 #(4.01cm rez)
    MARCHING_CUBES_BOUND: [[-0.1,8.6],[-0.1,8.9],[-0.3,3.3]]
    FRAME_SAMPLING_RATE: 1
    KEEP_DATA_ON_CPU: True
RENDERER: #here for the hyper-params
    NAME: "RendererInstantNGP" # implemented in NGP
    IMAGE_H: 480
    IMAGE_W: 640
    FX: 577.590698
    FY: 578.729797
    CX: 318.905426
    CY: 242.683609
    SCALE: 0.028559381402596923
    OFFSET: [0.38067812, 0.51338871, 0.23494958]
    AABB_SCALE: 1
    DISTORTION:
        ENABLED: False
    NEAR: 0.0
    FAR: 8.0
VERSION: 2
