PARENT: "scannet.yml"
META:
    OUTPUT_DIR: "data"
    NAME_EXPERIMENT: "ScanNet_scene0106"
    RUN_ID: 0
DATASET:
    NAME: "ScannetDatasetInstantNGP"
    INPUT_FOLDER: "Datasets/scannet/scans/scene0106_00"
    CROP_SIZE:
        ENABLED: False
    CROP_EDGE:
        ENABLED: True
        VALUE: 10
    PNG_DEPTH_SCALE: 1000.
    POSES_FILENAME: "data/ScanNet_scene0106/0/poses_processed_NGP.json"
    SHARPNESS_FILENAME: "data/ScanNet_scene0106/0/preprocess_sharpness.json"
    NGP_PREPROCESSED_DATA_FILENAME: "data/ScanNet_scene0106/0/preprocessed_dataset/transforms_with_poses.json"
    POSES_SCALE: 1.673336194834593
    POSES_CENTER_POINT: [1.42489763, -6.55566656, 0.58486049]
    POSES_UP_VECTOR: [-0.03174108, -0.09655287, -0.99482162]
    DESIRED_RESOLUTION: 320 #(3.97cm rez)
    MARCHING_CUBES_BOUND: [[-0.3,9.6],[-0.3,9.4],[-0.3,3.5]]
    FRAME_SAMPLING_RATE: 1
    KEEP_DATA_ON_CPU: False
RENDERER: #here for the hyper-params
    NAME: "RendererInstantNGP" # implemented in NGP
    IMAGE_H: 480
    IMAGE_W: 640
    FX: 577.590698
    FY: 578.729797
    CX: 318.905426
    CY: 242.683609
    SCALE: 0.04702192054141836
    OFFSET: [0.55980232, 0.3125767, 0.29177238] 
    AABB_SCALE: 1
    DISTORTION:
        ENABLED: False
    NEAR: 0.0
    FAR: 8.0
VERSION: 2
