PARENT: "scannet.yml"
META:
    OUTPUT_DIR: "data"
    NAME_EXPERIMENT: "ScanNet_scene0181"
    RUN_ID: 0
DATASET:
    NAME: "ScannetDatasetInstantNGP"
    INPUT_FOLDER: "Datasets/scannet/scans/scene0181_00"
    CROP_SIZE:
        ENABLED: False
    CROP_EDGE:
        ENABLED: True
        VALUE: 10
    PNG_DEPTH_SCALE: 1000.
    POSES_FILENAME: "data/ScanNet_scene0181/0/poses_processed_NGP.json"
    SHARPNESS_FILENAME: "data/ScanNet_scene0181/0/preprocess_sharpness.json"
    NGP_PREPROCESSED_DATA_FILENAME: "data/ScanNet_scene0181/0/preprocessed_dataset/transforms_with_poses.json"
    POSES_SCALE: 3.178310400265018
    POSES_CENTER_POINT: [5.50443868, -0.45174517, 1.41403765]
    POSES_UP_VECTOR: [-0.0210435, 0.05467129, -0.99828264]
    DESIRED_RESOLUTION: 352 #(4.06cm rez)
    MARCHING_CUBES_BOUND: [[-0.3,8.2],[-0.3,7.3],[-0.3,2.8]]
    FRAME_SAMPLING_RATE: 1
    KEEP_DATA_ON_CPU: False
RENDERER: #here for the hyper-params
    NAME: "RendererInstantNGP" # implemented in NGP
    IMAGE_H: 480
    IMAGE_W: 640
    FX: 577.590698
    FY: 578.729797
    CX: 318.905426
    CY: 242.683609
    SCALE: 0.021990075480517242
    OFFSET: [0.26362736, 0.65094244, 0.14512491] 
    AABB_SCALE: 1
    DISTORTION:
        ENABLED: False
    NEAR: 0.0
    FAR: 8.0
VERSION: 2
