PARENT: "replica.yml"
META:
    OUTPUT_DIR: "data"
    NAME_EXPERIMENT: "Replica_office4"
    RUN_ID: 0
DATASET:
    NAME: "ReplicaDatasetInstantNGP"
    INPUT_FOLDER: "Datasets/Replica/office4"
    CROP_SIZE:
        ENABLED: False
    CROP_EDGE:
        ENABLED: False
    PNG_DEPTH_SCALE: 6553.5
    POSES_FILENAME: "data/Replica_office4/0/poses_processed_NGP.json"
    SHARPNESS_FILENAME: "data/Replica_office4/0/preprocess_sharpness.json"
    NGP_PREPROCESSED_DATA_FILENAME: "data/Replica_office4/0/preprocessed_dataset/transforms_with_poses.json"
    POSES_SCALE: 3.3507352515103945
    POSES_CENTER_POINT: [-2.2305805, -0.82333344, 0.28303096]
    POSES_UP_VECTOR: [-0.03286978, -0.03194045, -0.99894914]
    DESIRED_RESOLUTION: 656 #(1cm rez)
    MARCHING_CUBES_BOUND: [[-1.3,5.4],[-2.4,4.3],[-1.3,1.7]] 
    FRAME_SAMPLING_RATE: 1
    KEEP_DATA_ON_CPU: False
RENDERER: #here for the hyper-params
    NAME: "RendererInstantNGP" # implemented in NGP
    IMAGE_H: 680
    IMAGE_W: 1200
    FX: 600.0
    FY: 600.0
    CX: 599.5
    CY: 339.5
    SCALE: 0.04551215823238897
    OFFSET: [0.47886155, 0.50499268, 0.27758825]
    AABB_SCALE: 1
    DISTORTION:
        ENABLED: False
    NEAR: 0.0
    FAR: 10.0
VERSION: 2
