PARENT: "replica.yml"
META:
    OUTPUT_DIR: "data"
    NAME_EXPERIMENT: "Replica_room0"
    RUN_ID: 0
DATASET:
    NAME: "ReplicaDatasetInstantNGP"
    INPUT_FOLDER: "Datasets/Replica/room0"
    CROP_SIZE:
        ENABLED: False
    CROP_EDGE:
        ENABLED: False
    PNG_DEPTH_SCALE: 6553.5
    POSES_FILENAME: "data/Replica_room0/0/poses_processed_NGP.json"
    SHARPNESS_FILENAME: "data/Replica_room0/0/preprocess_sharpness.json"
    NGP_PREPROCESSED_DATA_FILENAME: "data/Replica_room0/0/preprocessed_dataset/transforms_with_poses.json"
    POSES_SCALE: 3.600305736663454
    POSES_CENTER_POINT: [1.56852486, -2.40284289, 0.23298948]
    POSES_UP_VECTOR: [-0.00857089, 0.09183588, -0.99573727]
    DESIRED_RESOLUTION: 861 #(1cm rez)
    MARCHING_CUBES_BOUND: [[-1.0,7.0],[-1.3,3.7],[-1.7,1.4]] 
    FRAME_SAMPLING_RATE: 1
    KEEP_DATA_ON_CPU: False
RENDERER: #here for the hyper-params
    NAME: "RendererInstantNGP" # implemented in NGP
    IMAGE_H: 680
    IMAGE_W: 1200
    FX: 600.0
    FY: 600.0
    CX: 599.5
    CY: 339.5
    SCALE: 0.03227419817607659
    OFFSET: [0.33449632, 0.53736376, 0.21779678] 
    AABB_SCALE: 1
    DISTORTION:
        ENABLED: False
    NEAR: 0.0
    FAR: 10.0
VERSION: 2
