PARENT: "replica.yml"
META:
    OUTPUT_DIR: "data"
    NAME_EXPERIMENT: "Replica_office2"
    RUN_ID: 0
DATASET:
    NAME: "ReplicaDatasetInstantNGP"
    INPUT_FOLDER: "Datasets/Replica/office2"
    CROP_SIZE:
        ENABLED: False
    CROP_EDGE:
        ENABLED: False
    PNG_DEPTH_SCALE: 6553.5
    POSES_FILENAME: "data/Replica_office2/0/poses_processed_NGP.json"
    SHARPNESS_FILENAME: "data/Replica_office2/0/preprocess_sharpness.json"
    NGP_PREPROCESSED_DATA_FILENAME: "data/Replica_office2/0/preprocessed_dataset/transforms_with_poses.json"
    POSES_SCALE: 3.292932963991401
    POSES_CENTER_POINT: [-0.84375603, -0.94201695, 0.07787779]
    POSES_UP_VECTOR: [-0.2063677, -0.07780158, -0.97537649]
    DESIRED_RESOLUTION: 850 #(1cm rez)
    MARCHING_CUBES_BOUND: [[-3.5,3.1],[-2.9,5.4],[-1.3,1.6]] 
    FRAME_SAMPLING_RATE: 1
    KEEP_DATA_ON_CPU: False
RENDERER: #here for the hyper-params
    NAME: "RendererInstantNGP" # implemented in NGP
    IMAGE_H: 680
    IMAGE_W: 1200
    FX: 600.0
    FY: 600.0
    CX: 599.5
    CY: 339.5
    SCALE: 0.0357431875220929
    OFFSET: [0.49359662, 0.36046472, 0.27749376]
    AABB_SCALE: 1
    DISTORTION:
        ENABLED: False
    NEAR: 0.0
    FAR: 10.0
VERSION: 2
