MODEL:
    NERF_ARCHITECTURE: "InstantNGP"
    INSTANT_NGP_CONFIG_FILE: "configs/instant_ngp_configs.json"
    DEPTH_SUPERVISION_LAMBDA: 1.
    DEPTH_SUPERVISION_LAMBDA_TRACKING: 1.
    RGB_SUPERVISION_LAMBDA: 1.
    RGB_SUPERVISION_LAMBDA_TRACKING: 1.

    USE_SDF: False
    USE_VOL_SDF: False
    USE_STYLE_SDF: False
    USE_COSLAM_SDF: False
    SDF_TRUNCATION_DISTANCE: 0.1
    SDF_BETA: 0.1
    USE_SDF_LOSS: False
    USE_SDF_LOSS_TRACKING: False
    SDF_SUPERVISION_LAMBDA: 1000.
    SDF_SUPERVISION_LAMBDA_TRACKING: 1000.0
    USE_SDF_FREE_SPACE_LOSS: False
    USE_SDF_FREE_SPACE_LOSS_TRACKING: False
    SDF_FREE_SPACE_SUPERVISION_LAMBDA: 10.
    SDF_FREE_SPACE_SUPERVISION_LAMBDA_TRACKING: 10.

    USE_FREE_SPACE_LOSS: False
    USE_FREE_SPACE_LOSS_TRACKING: False
    FREE_SPACE_SUPERVISION_LAMBDA: 0.0
    FREE_SPACE_SUPERVISION_LAMBDA_TRACKING: 0.0
    FREE_SPACE_SUPERVISION_DISTANCE: 0.1

    USE_CUSTOM_RAY_MARCHING: False
    N_SAMPLES_FOR_REGULAR_POINT_SAMPLING: 128
    USE_DEPTH_GUIDED_SAMPLING: True
    TRUNCATION_DISTANCE_FOR_DEPTH_GUIDED_SAMPLING: 0.05
    NUM_SAMPLES_FOR_DEPTH_GUIDED_SAMPLING: 32

    USE_POSE_SCHEDULER_IN_MAPPING: False
    POSE_SCHEDULER_COEF: 0.33
    POSE_SCHEDULER_NORM: 128
    CONE_ANGLE_CONSTANT: 0.004
    USE_GRADIENT_CLIPPING_EXTRINSICS: True
    DENSITY_GRID_DECAY: 0.95
    USE_DENSITY_IN_POINT_SAMPLING: True

    USE_DS_NERF_LOSS: True
    USE_DS_NERF_LOSS_TRACKING: True
    DS_NERF_LOSS_LAMBDA: 0.5
    DS_NERF_LOSS_LAMBDA_TRACKING: 0.5
    DS_NERF_LOSS_DEPTH_SIGMA: 0.02
    DS_NERF_USE_SECH2_DIST: True
    DS_NERF_SECH2_SCALE: 10000.0

    DENSITY_ACTIVATION: "Exponential"
    MESH_RESOLUTION: 256
    MESH_RESOLUTION_METERS: 0.
    MESH_THRESH: 5.0

    USE_MEDIAN_DEPTH: True
MAPPER:
    NAME: "MapperInstantNGP_C2FBA"
    DO_LOCAL_MAPPING: True
    LOCAL_MAPPING_ITERATIONS: 16
    MAPPING_ITERATIONS: 1000
    MAX_FRAMES_PER_ITER: 5
    KEYFRAME_SELECTION_METHOD: "all"
    MARGIN_SAMPLE_WIDTH: 5
    MARGIN_SAMPLE_HEIGHT: 5
    DO_BA_WHILE_MAPPING: True
    DO_BA_WHILE_LOCAL_MAPPING: True
    MAX_GRID_LEVEL_RAND_TRAINING: False
    MAX_GRID_LEVEL_FACTOR: 1.0
    EXTRINSIC_LEARNING_RATE_POS: 2.5e-4
    EXTRINSIC_LEARNING_RATE_ROT: 7.5e-4
    NUM_RAYS_TO_SAMPLE: 4096
    NO_NUM_RAYS_IMPOSED_ON_FIRST_FRAME: False
    SAMPLE_IMAGE_PROPORTIONAL_TO_ERROR: False
    NUM_STEPS_BETWEEN_ERROR_MAP_UPDATE: 5
    TRACKING_HYPERPARAMETERS_FILE: "configs/TUM/mapping_hyperparams/c2f_lvl_2_light.json"
    #TRACKING_HYPERPARAMETERS_FILE: "configs/TUM/mapping_hyperparams/no_c2f.json"
    TARGET_BATCH_SIZE: 128000
    N_STEPS_BETWEEN_CAM_UPDATES: 2
    BA_MODE: 1
    DEBUG: False
RUNNER:
    NAME: "RunnerInstantNGPSequentialCoarse2Fine"
    SKIP_MAPPING_FIRST_IMAGE: False
    NUM_MAPPING_ITERATIONS_FIRST_IMAGE: 300
    TARGET_BATCH_SIZE_FIRST_IMAGE: 256000
    MAPPING_VISUALS_DIRNAME: 'mapping_viz'
    POSES_DIRNAME: 'poses'
    MESHES_DIRNAME: 'meshes'
    MODEL_CHECKPOINT_DIRNAME: 'models'
    LOGS_DIRNAME: 'logs'
    VIZ: False
    SAVE_VIZ_EVERY: 20
    KEYFRAME_MOTION_FILTER_THRESH: 8.
    CONSTANT_SPEED_ASSUMPTION: True
    VERBOSE: False
    DO_ADDITIONAL_LOCAL_BA: False
    SAVE_TB_LOGS: False
    ADD_FINAL_GIANT_BA: False
    DO_ADDITIONAL_LOCAL_FINETUNING: False
    LOCAL_FINETUNING_RATE: 1
    DO_DECODER_ONLY_PRETRAINING: False
    MAPPING_RATE: 5
    SAVE_MODELS: False
    SAVE_MODELS_RATE: 50
    USE_GT_CAMERA_POSES_FOR_MAPPING: False
    KF_MOTION_BASED_SELECTION: False
    KF_SELECTION_RATE: 5
    KF_SELECTION_RATE_MAX: 50
    SAVE_MESHES: False
    SAVE_MESHES_RATE: 100
    USE_SHARPNESS_IN_KF_SELECTION: False
    SHARPNESS_THRESH: 100.
    ADD_MOTION_ONLY_BA_TRAJECTORY_FILLER: False
    MOTION_ONLY_BA_ITERATIONS: 32
    USE_INITIALIZATION: False
    INITIALIZATION_ITERATIONS: 50
TRACKER:
    NAME: "TrackerInstantNGPCoarse2FineIfLoss"
    SEPARATE_POS_AND_ROT_LR: True
    POS_LR: 5.e-4
    ROT_LR: 1.5e-3
    LR: 2.e-3
    NUM_RAYS_TO_SAMPLE: 2048
    MARGIN_SAMPLE_WIDTH: 40
    MARGIN_SAMPLE_HEIGHT: 40
    TRACKING_HYPERPARAMETERS_FILE: "configs/TUM/tracking_hyperparams/c2f_lvl_2_light.json"
    #TRACKING_HYPERPARAMETERS_FILE: "configs/TUM/tracking_hyperparams/no_c2f.json"
    INSTANT_NGP_TRACKING_MODE: 1
    USE_DEPTH_VAR_IN_DEPTH_LOSS: False
    USE_IF_LOSS: True
    TARGET_BATCH_SIZE: 128000
    DEBUG: False
BUNDLE_ADJUSTMENTS:
    LOCAL_BA:
        NAME: "BundleAdjustementNGP"
        NUM_ITERATIONS: 100
        MARGIN_SAMPLE_WIDTH: 0
        MARGIN_SAMPLE_HEIGHT: 0
        MAX_GRID_LEVEL_RAND_TRAINING: False
        EXTRINSIC_LEARNING_RATE: 1.e-3
        SAMPLE_IMAGE_PROPORTIONAL_TO_ERROR: False
        NUM_RAYS_TO_SAMPLE: 4096
        TARGET_BATCH_SIZE: 512000
        N_STEPS_BETWEEN_CAM_UPDATES: 32
        BA_MODE: 1
        HYPERPARAMETERS_FILE: "configs/TUM/ba_hyperparams/no_c2f.json"
        MIN_RAYS_PER_IMAGE: 4096
        USE_RAY_COUNTERS_PER_IMAGE: False
EVALUATOR:
    NAME: "EvaluatorATEInstantNGP"
VERSION: 2
